name: cooldown_button
publish_to: none
version: 0.2.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  badges: 3.1.1
  flutter_countdown_timer: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
flutter: