name: cooldown_button
publish_to: none
version: 0.3.8

environment:
  sdk: '>=3.4.0-24.0.dev <4.0.0'
  flutter: ">=3.19.0-5.0.pre.44"

dependencies:
  flutter:
    sdk: flutter
  badges: 3.1.1
  flutter_countdown_timer: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
flutter: