name: cooldown_button
publish_to: none
version: 0.3.9

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=3.16.7"

dependencies:
  flutter:
    sdk: flutter
  badges: 3.1.2
  flutter_countdown_timer: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
flutter: